baseURL = "https://russo-con-azzurra.vercel.app"
languageCode = "it"
title = "Russo con Azzurra"
theme = "hugo-book"

[params]
  BookTheme = 'auto'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
